flowchart TD
    start(( Início )) --> input[\ Digite sua Nota \]
    input --> verification{ Nota >= 50? }
    verification --> |Sim| A[/ Aprovado /]
    verification --> |Não| B[/ Reprovado /]
    A --> finish([ Fim ])
    B --> finish